version: "3.8"
services:
  anthropic-demo:
    image: ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${HOME}/.anthropic:/home/computeruse/.anthropic
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    tty: true # Ensures the container runs in interactive mode
